---
- name: Create a VIP, pool and pool members
  hosts: lb
  connection: local
  gather_facts: no

  tasks:
    - name: Setup provider
      ansible.builtin.set_fact:
        provider:
          password: zingoPLUS
          server: "{{ ansible_host }}"
          user: admin
          validate_certs: no
          server_port: 443
    - name: Find Active Machine
      f5networks.f5_modules.bigip_command:
        provider: "{{ provider }}"
        match: any
        warn: no
        commands:
          - bash -c "cat /var/prompt/ps1"
      register: result

    - debug:
        var: result.stdout

    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: "{{ vip_name }}_pool"
        partition: "{{ partition }}" #partition: DC-NG-RX-PROD
        slow_ramp_time: 120
      delegate_to: localhost
      when: '"Active" in result.stdout'

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        #description: foo-vip
        destination: "{{ vip_ip }}"
        name: "{{ vip_name }}"
        pool: "{{ vip_name }}_pool"
        port: 80
        partition: "{{ partition }}" #partition: DC-NG-RX-PROD
        snat: Automap
        profiles:
          - http
          - clientssl
      delegate_to: localhost
      when: '"Active" in result.stdout'
    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: "{{ vip_name }}_pool"
        port: 80
        partition: "{{ partition }}"
      with_items:
        - host: 10.10.10.10
          name: web01
        - host: 10.10.10.20
          name: web02
      delegate_to: localhost
      when: '"Active" in result.stdout'
